# Generated by Django 5.2.7 on 2026-07-24 10:14
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]

    operations = [
        CreateExtension("vector"),
    ]
